// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) 
	{
	    int n=Integer.parseInt(args[0]);
		int Big=0,Lil=0;
		for(int i=0;i<n;i++)
		{
			if(Math.random()>0.5)
			{
				Big++;

			}
			else
			{
				Lil++;

			}


		}
		if(Lil!=0 && Big!=0)
		{
			System.out.print((double)Big/Lil);
		}
		
	}
}
